name: Feature Request

title: Change this title, poorly formatted issues will not be handled

description: Request a new feature

labels: feature-request

body:

- type: dropdown
  attributes:
    label: Plugin
    description: In which plugin do you want to add a feature?
    multiple: true
    options:
      - label: DCController
  validations:
    required: true

- type: textarea
  attributes:
    label: Requested Feature
    placeholder: Describe the feature you would like to see implemented!
  validations:
    required: true

- type: textarea
  attributes:
    label: Possible implementation
    placeholder: Describe a potential method of implementing this feature
